name: client
description: "Official pasby example code"
publish_to: 'none' 

version: 0.0.1+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_translate: ^4.0.4
  auto_translator: ^2.0.0
  responsive_framework: ^1.1.1
  go_router: ^13.1.0
  flutter_riverpod: ^2.5.1
  hooks_riverpod: ^2.4.10
  url_strategy: ^0.2.0
  flutter_spinkit: ^5.2.0
  labs:
    git: https://github.com/Finsel-DGI/labs.git
  labs_web:
    git: https://github.com/Finsel-DGI/web_library.git
  get_it: ^7.7.0
  sizer: ^2.0.15
  riverbloc: ^2.2.0
  flutter_hooks: ^0.18.6
  rive: ^0.13.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_gen_runner:
  json_serializable: ^6.7.1
  build_runner: ^2.3.3
  flutter_lints: ^3.0.0

flutter_gen:
  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
    lottie: true

flutter:
  generate: true
  uses-material-design: true
  fonts:
    - family: Inter
      fonts:
        - asset: packages/labs_web/fonts/Inter/Inter-Bold.ttf
        - asset: packages/labs_web/fonts/Inter/Inter-Medium.ttf
    - family: Inter-Medium
      fonts:
        - asset: packages/labs_web/fonts/Inter/Inter-Medium.ttf
    - family: Libre
      fonts:
        - asset: packages/labs/fonts/LibreFranklin-VariableFont_wght.ttf
        - asset: packages/labs/fonts/LibreFranklin-Italic-VariableFont_wght.ttf

  assets:
    - assets/i18n/
    - assets/rive/
    - assets/svg/