name: logistics
publish_to: none

environment:
  sdk: '>=3.3.0 <4.0.0'

dev_dependencies:
  flutter_lints: ^2.0.1
  test: ^1.22.1
  build_runner: ^2.3.2

dependencies:
  flutter:
    sdk: flutter
  http: any
  intl: ^0.18.0
  jiffy: ^5.0.0
  hooks_riverpod: ^2.1.1
  flutter_hooks: ^0.18.5+1
  gap: ^3.0.1
  qr_flutter: 4.0.0
  shared_preferences: ^2.0.16
  sizer: ^2.0.15
  drop_cap_text: ^1.1.3
  flutter_spinkit: ^5.1.0
  image_picker: ^0.8.6
  url_launcher: ^6.1.7
  shimmer: ^2.0.0
  path: ^1.8.3
  age_calculator: ^1.0.0
  scroll_to_index: ^3.0.1
  highlight_text: ^1.6.0
  logger: ^1.1.0
  dio: ^5.3.3
  getwidget: ^4.0.0
  seo_renderer: ^0.6.0

flutter:
  uses-material-design: true
  fonts:
    - family: Libre
      fonts:
        - asset: lib/fonts/LibreFranklin-VariableFont_wght.ttf
        - asset: lib/fonts/LibreFranklin-Italic-VariableFont_wght.ttf